# Generated by Django 4.2.6 on 2023-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyname',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
