# Generated by Django 4.2.6 on 2023-11-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('applied', 'APPLIED'), ('interview', 'INTERVIEW'), ('rejected', 'REJECTED'), ('accepted', 'ACCEPTED')], default='applied', max_length=16),
        ),
    ]
