# Generated by Django 4.2.6 on 2023-11-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=80),
        ),
    ]
