# Generated by Django 4.2.6 on 2023-12-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(default='', max_length=800),
        ),
    ]
