# Generated by Django 4.2.6 on 2023-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_note',
            field=models.TextField(blank=True, default='', max_length=800, null=True),
        ),
    ]
