# Generated by Django 4.2.6 on 2023-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_extra_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companyname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Applied', 'APPLIED'), ('Interview', 'INTERVIEW'), ('Rejected', 'REJECTED'), ('Accepted', 'ACCEPTED')], default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
